import type { Metadata } from "next";
import { draftMode } from "next/headers";
import { VisualEditing } from "next-sanity";

// import Header from "@/components/Header";
import { SanityLive } from "@/sanity/lib/live";
import DisableDraftMode from "@/components/DisableDraftMode";

import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {(await draftMode()).isEnabled && (
          <>
            <DisableDraftMode />
            <VisualEditing />
          </>
        )}

        <main>
          {/* <Header /> */}
          {children}
        </main>

        <SanityLive />
      </body>
    </html>
  );
}

